config/routes.rb
Rails.application.routes.draw do
  resources :moods
  root 'moods#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mood.rb
class Mood < ApplicationRecord
	#to load the worksheet
	def self.worksheet
		@session ||= GoogleDrive::Session.from_service_account_key("lib/client.rb")
		@spreadsheet ||= @session.spreadsheet_by_title("Toy App")
		@worksheet ||= @spreadsheet.worksheets.first
	end

  #to perform update on database table
	def self.perform
    rows = worksheet.rows
    (1...rows.count).each do |row|
     if rows[row][2] == "skip" ||  rows[row][2] == "complete"
       mood = Mood.find_by(id: rows[row][0])
       if mood
         mood.input_url = rows[row][1]
         mood.status = rows[row][2]
         mood.output_url = rows[row][3]
         mood.save
       end
     end
    end
  end

  #to insert and update in sheet
  def insert_and_update(input_url)
    worksheet = Mood.worksheet
    worksheet.insert_rows(worksheet.num_rows+1,[input_url])
    if worksheet.save
    	input_url << "processed"
      worksheet.update_cells(worksheet.num_rows,1,[input_url])
    	self.status = "processed"
    	self.save
    	worksheet.save
  	end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  before_action :set_mood, only: [:show, :edit, :update, :destroy]

  # GET /moods
  # GET /moods.json
  def index
    #sorting according the status
    if params['sort']
      @moods = Mood.order("status #{params['sort']}")
    else
      @moods = Mood.all  #default
      Mood.delay.perform #update database if any record processed does not work all time
    end
  end

  # GET /moods/1
  # GET /moods/1.json
  def show
  end

  # GET /moods/new
  def new
    @mood = Mood.new
  end

 
  # POST /moods
  # POST /moods.json
  def create
    @mood = Mood.new(mood_params)
    
    respond_to do |format|
      if @mood.save
        @mood.delay.insert_and_update([@mood.id,mood_params["input_url"]])
        UserMailer.delay.process_mood
        format.html { redirect_to moods_url, notice: 'Mood was successfully created.' }
        format.json { render :show, status: :created, location: @mood }
      else
        format.html { render :new }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_mood
      @mood = Mood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mood_params
      params.require(:mood).permit(:input_url, :status, :output_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/views/home/index.html.erb
<%= %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoodMusic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="container">
        <div class="jumbotron">
          <h1>Music Mood App</h1>
        </div>
    	<%= yield %>
    </div>
  </body>
</html>

app/views/moods/_form.html.erb
<%= form_with(model: mood, local: true) do |form| %>
  <% if mood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mood.errors.count, "error") %> prohibited this mood from being saved:</h2>

      <ul>
      <% mood.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :input_url %>
    <%= form.text_field :input_url, id: :mood_input_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/moods/index.html.erb
<%= react_component 'Main' %>

app/views/moods/new.html.erb
<h1>New Mood</h1>

<%= render 'form', mood: @mood %>

<%= link_to 'Back', moods_path %>